# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Search_Weather_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Search_Weather_MVVM
	pod 'Alamofire'
  pod 'SDWebImage'
end
